// Code generated by MockGen. DO NOT EDIT.
// Source: engine.go

// Package scan is a generated GoMock package.
package scan

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gopacket "github.com/google/gopacket"
	packet "github.com/v-byte-cpu/sx/pkg/packet"
)

// MockPacketSource is a mock of PacketSource interface.
type MockPacketSource struct {
	ctrl     *gomock.Controller
	recorder *MockPacketSourceMockRecorder
}

// MockPacketSourceMockRecorder is the mock recorder for MockPacketSource.
type MockPacketSourceMockRecorder struct {
	mock *MockPacketSource
}

// NewMockPacketSource creates a new mock instance.
func NewMockPacketSource(ctrl *gomock.Controller) *MockPacketSource {
	mock := &MockPacketSource{ctrl: ctrl}
	mock.recorder = &MockPacketSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPacketSource) EXPECT() *MockPacketSourceMockRecorder {
	return m.recorder
}

// Packets mocks base method.
func (m *MockPacketSource) Packets(ctx context.Context, r *Range) <-chan *packet.BufferData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets", ctx, r)
	ret0, _ := ret[0].(<-chan *packet.BufferData)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockPacketSourceMockRecorder) Packets(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockPacketSource)(nil).Packets), ctx, r)
}

// MockMethod is a mock of Method interface.
type MockMethod struct {
	ctrl     *gomock.Controller
	recorder *MockMethodMockRecorder
}

// MockMethodMockRecorder is the mock recorder for MockMethod.
type MockMethodMockRecorder struct {
	mock *MockMethod
}

// NewMockMethod creates a new mock instance.
func NewMockMethod(ctrl *gomock.Controller) *MockMethod {
	mock := &MockMethod{ctrl: ctrl}
	mock.recorder = &MockMethodMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMethod) EXPECT() *MockMethodMockRecorder {
	return m.recorder
}

// Packets mocks base method.
func (m *MockMethod) Packets(ctx context.Context, r *Range) <-chan *packet.BufferData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets", ctx, r)
	ret0, _ := ret[0].(<-chan *packet.BufferData)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockMethodMockRecorder) Packets(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockMethod)(nil).Packets), ctx, r)
}

// ProcessPacketData mocks base method.
func (m *MockMethod) ProcessPacketData(data []byte, ci *gopacket.CaptureInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPacketData", data, ci)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPacketData indicates an expected call of ProcessPacketData.
func (mr *MockMethodMockRecorder) ProcessPacketData(data, ci interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPacketData", reflect.TypeOf((*MockMethod)(nil).ProcessPacketData), data, ci)
}
