// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/v-byte-cpu/sx/pkg/scan (interfaces: PacketSource,Scanner)
//
// Generated by this command:
//
//	mockgen -package scan -destination=mock_engine_test.go . PacketSource,Scanner
//

// Package scan is a generated GoMock package.
package scan

import (
	context "context"
	reflect "reflect"

	packet "github.com/v-byte-cpu/sx/pkg/packet"
	gomock "go.uber.org/mock/gomock"
)

// MockPacketSource is a mock of PacketSource interface.
type MockPacketSource struct {
	ctrl     *gomock.Controller
	recorder *MockPacketSourceMockRecorder
	isgomock struct{}
}

// MockPacketSourceMockRecorder is the mock recorder for MockPacketSource.
type MockPacketSourceMockRecorder struct {
	mock *MockPacketSource
}

// NewMockPacketSource creates a new mock instance.
func NewMockPacketSource(ctrl *gomock.Controller) *MockPacketSource {
	mock := &MockPacketSource{ctrl: ctrl}
	mock.recorder = &MockPacketSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPacketSource) EXPECT() *MockPacketSourceMockRecorder {
	return m.recorder
}

// Packets mocks base method.
func (m *MockPacketSource) Packets(ctx context.Context, r *Range) <-chan *packet.BufferData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets", ctx, r)
	ret0, _ := ret[0].(<-chan *packet.BufferData)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockPacketSourceMockRecorder) Packets(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockPacketSource)(nil).Packets), ctx, r)
}

// MockScanner is a mock of Scanner interface.
type MockScanner struct {
	ctrl     *gomock.Controller
	recorder *MockScannerMockRecorder
	isgomock struct{}
}

// MockScannerMockRecorder is the mock recorder for MockScanner.
type MockScannerMockRecorder struct {
	mock *MockScanner
}

// NewMockScanner creates a new mock instance.
func NewMockScanner(ctrl *gomock.Controller) *MockScanner {
	mock := &MockScanner{ctrl: ctrl}
	mock.recorder = &MockScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanner) EXPECT() *MockScannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockScanner) Scan(ctx context.Context, r *Request) (Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx, r)
	ret0, _ := ret[0].(Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockScannerMockRecorder) Scan(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockScanner)(nil).Scan), ctx, r)
}
