// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/v-byte-cpu/sx/pkg/packet (interfaces: Sender,Receiver)
//
// Generated by this command:
//
//	mockgen -package scan -destination=mock_sendreceiver_test.go github.com/v-byte-cpu/sx/pkg/packet Sender,Receiver
//

// Package scan is a generated GoMock package.
package scan

import (
	context "context"
	reflect "reflect"

	packet "github.com/v-byte-cpu/sx/pkg/packet"
	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// SendPackets mocks base method.
func (m *MockSender) SendPackets(ctx context.Context, in <-chan *packet.BufferData) (<-chan any, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPackets", ctx, in)
	ret0, _ := ret[0].(<-chan any)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// SendPackets indicates an expected call of SendPackets.
func (mr *MockSenderMockRecorder) SendPackets(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPackets", reflect.TypeOf((*MockSender)(nil).SendPackets), ctx, in)
}

// MockReceiver is a mock of Receiver interface.
type MockReceiver struct {
	ctrl     *gomock.Controller
	recorder *MockReceiverMockRecorder
	isgomock struct{}
}

// MockReceiverMockRecorder is the mock recorder for MockReceiver.
type MockReceiverMockRecorder struct {
	mock *MockReceiver
}

// NewMockReceiver creates a new mock instance.
func NewMockReceiver(ctrl *gomock.Controller) *MockReceiver {
	mock := &MockReceiver{ctrl: ctrl}
	mock.recorder = &MockReceiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceiver) EXPECT() *MockReceiverMockRecorder {
	return m.recorder
}

// ReceivePackets mocks base method.
func (m *MockReceiver) ReceivePackets(ctx context.Context) <-chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceivePackets", ctx)
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// ReceivePackets indicates an expected call of ReceivePackets.
func (mr *MockReceiverMockRecorder) ReceivePackets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceivePackets", reflect.TypeOf((*MockReceiver)(nil).ReceivePackets), ctx)
}
