// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package scan

import (
	"github.com/v-byte-cpu/sx/pkg/packet"
)

// Injectors from inject_engine.go:

func SetupEngine(rw packet.ReadWriter, m Method) *Engine {
	sender := packet.NewSender(rw)
	receiver := packet.NewReceiver(rw, m)
	engine := NewEngine(m, sender, receiver)
	return engine
}

// inject_engine.go:

type Method interface {
	PacketSource
	packet.Processor
}
