version: 2

project_name: sx

gomod:
  proxy: true

builds:
  - id: sx
    binary: sx
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -linkmode external -extldflags '-static' -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: sx

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  disable: true

release:
  prerelease: auto
  mode: replace
  name_template: "{{ .Version }}"
